# Generated by Django 6.0.6 on 2026-07-20 16:33

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membership_duration', models.PositiveSmallIntegerField(choices=[(1, '1 Month'), (2, '2 Months'), (3, '3 Months'), (4, '4 Months'), (5, '5 Months'), (6, '6 Months'), (7, '7 Months'), (8, '8 Months'), (9, '9 Months'), (10, '10 Months'), (11, '11 Months'), (12, '1 Year')])),
                ('payment_date', models.DateField(default=django.utils.timezone.now)),
                ('expiry_date', models.DateField()),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_type', models.CharField(choices=[('Cash', 'Cash'), ('UPI', 'UPI'), ('Card', 'Card'), ('Bank', 'Bank')], max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='members.member')),
            ],
        ),
    ]
