# Generated by Django 6.0.6 on 2026-07-16 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_reminder', models.BooleanField(default=True)),
                ('reminder_days', models.PositiveIntegerField(default=3)),
                ('template', models.TextField(default='\n\n        Hello {member_name},\n\n        Your membership will expire on {expiry_date}.\n\n        Membership ID : {membership_id}\n\n        Please renew your membership.\n\n        Thank you,\n        GymPro\n\n        ')),
            ],
        ),
    ]
