# Generated by Django 6.0.6 on 2026-07-25 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0002_whatsappsetting_trainer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsappsetting',
            name='template',
            field=models.TextField(default='\n\n        Hello {member_name},\n\n        Your membership will expire on {expiry_date}.\n\n        Membership ID : {membership_id}\n\n        Please renew your membership.\n\n        Thank you,\n        {gym_name}\n\n        '),
        ),
    ]
